---
charon_test:
  hosts:
    main:
      ansible_host: "192.5.86.155"
      ansible_user: cc
      ansible_ssh_private_key_file: "/Users/akhileshraj/.ssh/id_ed25519"

    cluster-2:
      ansible_host: "10.140.83.239"
      ansible_user: cc
      # Add the `-i` flag to explicitly include the identity file (private key) for the jump host.
      ansible_ssh_common_args: '-o ProxyJump=cc@192.5.86.155 -o IdentityFile=/Users/akhileshraj/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
      ansible_ssh_private_key_file: "/Users/akhileshraj/.ssh/id_ed25519"